name = "conclave-backend"
main = "./src/index.ts"
compatibility_date = "2026-05-10"
preview_urls = true

[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = true
persist = true
head_sampling_rate = 1

[assets]
directory = "./client/dist"
binding = "ASSETS"
not_found_handling = "single-page-application"
run_worker_first = [ "/api/*" ]

[[durable_objects.bindings]]
name = "CONCLAVE_ROOM"
class_name = "ConclaveRoom"

[[migrations]]
tag = "v1"
new_sqlite_classes = [ "ConclaveRoom" ]

[[routes]]
custom_domain = true