name = "conclave-backend"
main = "src/index.ts"
compatibility_date = "2024-04-03"

[env.dev]
vars = { ENVIRONMENT = "dev" }

[[env.dev.durable_objects.bindings]]
name = "CONCLAVE_ROOM"
class_name = "ConclaveRoom"

[env.prod]
vars = { ENVIRONMENT = "prod" }

[[env.prod.durable_objects.bindings]]
name = "CONCLAVE_ROOM"
class_name = "ConclaveRoom"
